### PR TITLE
added info in footer

### LINKED ISSUE #1: add proper footer information in the home page.
Add proper footer information

### PR DESCRIPTION
**Pull request by SamikshaSankar**
Issue-2

### CODE REVIEW

**Comment by SayantaniDeb** [comment]
Looks good, thanks for contributing!

**Comment by SayantaniDeb** [comment]
Looks good, thanks for contributing!

**Comment by SayantaniDeb** [comment]
Hey, don't forget to add your details into the contributors page as well.

**Comment by SamikshaSankar** [comment]
@SayantaniDeb Can I update readme file...bcz most off the time we forgot to add contribution details so instead of manual adding Can I make changes so it's happened directly

**Pull request merged**
